replicaCount: 10
image:
  repository: danielrodriguess/nlw.journey.api
  pullPolicy: IfNotPresent
  tag: c4d1a2b
  containerPort: 8080
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ''
podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}
service:
  type: LoadBalancer
  port: 80
ingress:
  enabled: false
  className: ''
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi
autoscaling:
  enabled: true
  minReplicas: 10
  maxReplicas: 15
  targetCPUUtilizationPercentage: 75
volumes: []
volumeMounts: []
nodeSelector: {}
tolerations: []
affinity: {}
